[directory]
truncate_to_repo = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[package]
disabled = true

[battery]
disabled = true

[python]
symbol = " "

[nodejs]
symbol = " "

[git_branch]
symbol = " "

[conda]
disabled  = true
