[directory]
truncate_to_repo = true
truncation_length = 10

[character]
symbol = " "

[package]
disabled = true
symbol = " "

[battery]
disabled = true

[python]
symbol = " "

[nodejs]
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[git_branch]
symbol = " "

[conda]
symbol = " "

[docker]
symbol = " "
